import { useState, FormEvent } from "react";
import { useNavigate, Link } from "react-router";
import PageBreadcrumb from "../../components/common/PageBreadCrumb";
import PageMeta from "../../components/common/PageMeta";
import { studentAPI, mediaAPI } from "../../utils/api";
import { AngleLeftIcon } from "../../icons";
import Label from "../../components/form/Label";
import Input from "../../components/form/input/InputField";
import CreateStudentSidebar from "./CreateStudentSidebar";

export default function CreateStudent() {
  const navigate = useNavigate();
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [formData, setFormData] = useState({
    national_id_number: "",
    fullname: "",
    phone_number: "",
    dormitory: "",
    grade_level: "",
    guardian_name: "",
    is_active: true,
  });
  const [countryCode, setCountryCode] = useState<string>("+62");
  const [profileImage, setProfileImage] = useState<File | null>(null);

  const handleFormChange = (name: string, value: string | boolean) => {
    setFormData((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setError(null);

    // Client-side validation
    if (formData.national_id_number.trim().length === 0) {
      setError("NIK wajib diisi");
      return;
    }

    if (formData.fullname.trim().length < 2) {
      setError("Nama lengkap minimal 2 karakter");
      return;
    }

    setIsLoading(true);

    try {
      // Format phone number: combine country code with phone number
      let formattedPhoneNumber = null;
      if (formData.phone_number.trim()) {
        let phoneNum = formData.phone_number.trim();
        
        // Remove any existing country code prefix
        if (phoneNum.startsWith("+62")) {
          phoneNum = phoneNum.substring(3);
        } else if (phoneNum.startsWith("+1")) {
          phoneNum = phoneNum.substring(2);
        }
        
        // For Indonesian numbers (+62), format should be +62XXXXXXXXX (without leading 0)
        if (countryCode === "+62") {
          // Remove leading 0 if present
          if (phoneNum.startsWith("0")) {
            phoneNum = phoneNum.substring(1);
          }
          formattedPhoneNumber = "+62" + phoneNum;
        } else if (countryCode === "+1") {
          formattedPhoneNumber = "+1" + phoneNum;
        } else {
          formattedPhoneNumber = countryCode + phoneNum;
        }
      }

      // Create student (unique_code and qr_code will be auto-generated by backend)
      const createResponse = await studentAPI.createStudent({
        national_id_number: formData.national_id_number.trim(),
        fullname: formData.fullname.trim(),
        phone_number: formattedPhoneNumber || null,
        dormitory: formData.dormitory.trim() || null,
        grade_level: formData.grade_level.trim() || null,
        guardian_name: formData.guardian_name.trim() || null,
        is_active: formData.is_active,
      });

      if (!createResponse.success) {
        setError(createResponse.message || "Gagal membuat siswa");
        setIsLoading(false);
        return;
      }

      // Success - upload profile picture if provided
      if (createResponse.data?.id && profileImage) {
        try {
          await mediaAPI.uploadMedia(
            profileImage,
            'Student',
            createResponse.data.id,
            'profile-pictures'
          );
        } catch (uploadErr: any) {
          console.error('Error uploading profile picture:', uploadErr);
          // Continue even if upload fails
        }
      }

      // Redirect to view student page
      if (createResponse.data?.id) {
        navigate(`/students/${createResponse.data.id}`);
      } else {
        navigate("/students");
      }
    } catch (err: any) {
      setError("Terjadi kesalahan saat membuat siswa");
      console.error("Create student error:", err);
      setIsLoading(false);
    }
  };

  return (
    <>
      <PageMeta
        title="Create Student"
        description="Create new student"
      />
      <PageBreadcrumb
        pageTitle={
          <div className="flex items-center gap-2 font-normal text-base">
            <Link
              to="/students"
              className="text-gray-600 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-300"
            >
              Students
            </Link>
            <span className="text-gray-600">&gt;</span>
            <span>Create Student</span>
          </div>
        }
        hideBreadcrumb={true}
      />

      <div className="space-y-6">
        {/* Header with Title */}
        <div className="flex items-center justify-between">
          <h1 className="text-2xl font-bold text-gray-800 dark:text-white">
            Create New Student
          </h1>
        </div>

        {/* Main Content */}
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-4">
          {/* Left Sidebar */}
          <div className="lg:col-span-1">
            <CreateStudentSidebar
              profileImage={profileImage ? URL.createObjectURL(profileImage) : null}
              onProfileImageChange={setProfileImage}
            />
          </div>

          {/* Right Content Area */}
          <div className="lg:col-span-3">
            <div className="bg-white rounded-lg border border-gray-200 dark:bg-gray-800 dark:border-gray-700 p-6">
              <form onSubmit={handleSubmit}>
            <div className="space-y-5">
              {error && (
                <div className="p-3 text-sm text-red-600 bg-red-50 border border-red-200 rounded-lg dark:bg-red-900/20 dark:text-red-400 dark:border-red-800">
                  {error}
                </div>
              )}

              <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
                <div className="sm:col-span-2">
                  <Label>
                    NIK (Nomor Induk Kependudukan) <span className="text-error-500">*</span>
                  </Label>
                  <Input
                    type="text"
                    name="national_id_number"
                    value={formData.national_id_number}
                    onChange={(e) => handleFormChange(e.target.name, e.target.value)}
                    placeholder="Masukkan NIK"
                    disabled={isLoading}
                  />
                </div>

                <div className="sm:col-span-2">
                  <Label>
                    Nama Lengkap <span className="text-error-500">*</span>
                  </Label>
                  <Input
                    type="text"
                    name="fullname"
                    value={formData.fullname}
                    onChange={(e) => handleFormChange(e.target.name, e.target.value)}
                    placeholder="Masukkan nama lengkap"
                    disabled={isLoading}
                  />
                </div>

                <div className="sm:col-span-1">
                  <Label>Asrama</Label>
                  <Input
                    type="text"
                    name="dormitory"
                    value={formData.dormitory}
                    onChange={(e) => handleFormChange(e.target.name, e.target.value)}
                    placeholder="Masukkan asrama"
                    disabled={isLoading}
                  />
                </div>

                <div className="sm:col-span-1">
                  <Label>Kelas</Label>
                  <Input
                    type="text"
                    name="grade_level"
                    value={formData.grade_level}
                    onChange={(e) => handleFormChange(e.target.name, e.target.value)}
                    placeholder="Masukkan kelas"
                    disabled={isLoading}
                  />
                </div>


                <div className="sm:col-span-1">
                  <Label>No. Telepon</Label>
                  <div className="flex gap-2">
                    <select
                      className="px-3 py-2 text-sm border border-gray-300 rounded-lg bg-white dark:bg-gray-800 dark:border-gray-700 dark:text-white"
                      disabled={isLoading}
                      value={countryCode}
                      onChange={(e) => setCountryCode(e.target.value)}
                    >
                      <option value="+62">🇮🇩 +62</option>
                      <option value="+1">🇺🇸 +1</option>
                    </select>
                    <Input
                      type="tel"
                      name="phone_number"
                      value={formData.phone_number}
                      onChange={(e) => handleFormChange(e.target.name, e.target.value)}
                      placeholder="0821-3351-3522"
                      disabled={isLoading}
                      className="flex-1"
                    />
                  </div>
                </div>

                <div className="sm:col-span-1">
                  <Label>Nama Wali</Label>
                  <Input
                    type="text"
                    name="guardian_name"
                    value={formData.guardian_name}
                    onChange={(e) => handleFormChange(e.target.name, e.target.value)}
                    placeholder="Masukkan nama wali"
                    disabled={isLoading}
                  />
                </div>

                <div className="sm:col-span-2">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="is_active"
                      name="is_active"
                      checked={formData.is_active}
                      onChange={(e) => handleFormChange(e.target.name, e.target.checked)}
                      disabled={isLoading}
                      className="w-4 h-4 text-brand-500 bg-gray-100 border-gray-300 rounded focus:ring-brand-500 dark:focus:ring-brand-500 dark:ring-offset-gray-800 focus:ring-2 dark:bg-gray-700 dark:border-gray-600"
                    />
                    <Label htmlFor="is_active" className="cursor-pointer">
                      Aktif
                    </Label>
                  </div>
                </div>
              </div>

              {/* Bottom Action Buttons */}
              <div className="flex items-center justify-end gap-3 pt-6 mt-6 border-t border-gray-200 dark:border-gray-700">
                <button
                  type="button"
                  onClick={() => navigate("/students")}
                  disabled={isLoading}
                  className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed dark:bg-gray-800 dark:text-gray-400 dark:border-gray-700 dark:hover:bg-gray-700"
                >
                  <AngleLeftIcon className="w-4 h-4" />
                  Back
                </button>
                <button
                  type="submit"
                  disabled={isLoading}
                  className="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-brand-500 rounded-lg hover:bg-brand-600 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  <svg
                    className="w-4 h-4"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M12 4v16m8-8H4"
                    />
                  </svg>
                  {isLoading ? "Creating..." : "Create Student"}
                </button>
              </div>
            </div>
          </form>
        </div>
          </div>
        </div>
      </div>
    </>
  );
}

