"""update student & add qr_codes for laundry flow

Revision ID: 2f45b5b57567
Revises: c657d39ee6d5
Create Date: 2026-04-03 15:05:10.958899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f45b5b57567'
down_revision = 'c657d39ee6d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=True),
    sa.Column('token_qr', sa.String(length=255), nullable=False),
    sa.Column('dormitory', sa.String(length=255), nullable=True),
    sa.Column('qr_number', sa.String(length=50), nullable=True),
    sa.Column('unique_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_codes_dormitory'), 'qr_codes', ['dormitory'], unique=False)
    op.create_index(op.f('ix_qr_codes_student_id'), 'qr_codes', ['student_id'], unique=True)
    op.create_index(op.f('ix_qr_codes_token_qr'), 'qr_codes', ['token_qr'], unique=True)
    op.drop_constraint('orders_student_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'students', ['student_id'], ['id'], ondelete='RESTRICT')
    op.add_column('students', sa.Column('student_number', sa.String(length=255), nullable=False))
    op.drop_index('ix_students_national_id_number', table_name='students')
    op.drop_index('ix_students_qr_code', table_name='students')
    op.drop_index('ix_students_unique_code', table_name='students')
    op.create_index(op.f('ix_students_student_number'), 'students', ['student_number'], unique=True)
    op.drop_column('students', 'grade_level')
    op.drop_column('students', 'unique_code')
    op.drop_column('students', 'dormitory')
    op.drop_column('students', 'qr_code')
    op.drop_column('students', 'national_id_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('national_id_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('students', sa.Column('qr_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('dormitory', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('unique_code', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('grade_level', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_students_student_number'), table_name='students')
    op.create_index('ix_students_unique_code', 'students', ['unique_code'], unique=False)
    op.create_index('ix_students_qr_code', 'students', ['qr_code'], unique=False)
    op.create_index('ix_students_national_id_number', 'students', ['national_id_number'], unique=False)
    op.drop_column('students', 'student_number')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_student_id_fkey', 'orders', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_qr_codes_token_qr'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_student_id'), table_name='qr_codes')
    op.drop_index(op.f('ix_qr_codes_dormitory'), table_name='qr_codes')
    op.drop_table('qr_codes')
    # ### end Alembic commands ###

