"""update dormitory

Revision ID: 8ff810dddf2b
Revises: 2f45b5b57567
Create Date: 2026-04-03 15:25:44.001705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ff810dddf2b'
down_revision = '2f45b5b57567'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dormitories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dormitories_name'), 'dormitories', ['name'], unique=True)
    op.add_column('qr_codes', sa.Column('dormitory_id', sa.String(length=36), nullable=True))
    op.drop_index('ix_qr_codes_dormitory', table_name='qr_codes')
    op.create_index(op.f('ix_qr_codes_dormitory_id'), 'qr_codes', ['dormitory_id'], unique=False)
    op.create_foreign_key(None, 'qr_codes', 'dormitories', ['dormitory_id'], ['id'], ondelete='SET NULL')
    op.drop_column('qr_codes', 'dormitory')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_codes', sa.Column('dormitory', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'qr_codes', type_='foreignkey')
    op.drop_index(op.f('ix_qr_codes_dormitory_id'), table_name='qr_codes')
    op.create_index('ix_qr_codes_dormitory', 'qr_codes', ['dormitory'], unique=False)
    op.drop_column('qr_codes', 'dormitory_id')
    op.drop_index(op.f('ix_dormitories_name'), table_name='dormitories')
    op.drop_table('dormitories')
    # ### end Alembic commands ###

