"""add color table and link to qr_codes

Revision ID: b9ccf537992b
Revises: e4b5c6d7e8fa
Create Date: 2026-04-08 09:01:58.702061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ccf537992b'
down_revision = 'e4b5c6d7e8fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colors_name'), 'colors', ['name'], unique=True)
    op.alter_column('addons', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('qr_codes', sa.Column('color_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_qr_codes_color_id'), 'qr_codes', ['color_id'], unique=False)
    op.create_foreign_key('qr_codes_color_id_fkey', 'qr_codes', 'colors', ['color_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('qr_codes_color_id_fkey', 'qr_codes', type_='foreignkey')
    op.drop_index(op.f('ix_qr_codes_color_id'), table_name='qr_codes')
    op.drop_column('qr_codes', 'color_id')
    op.alter_column('addons', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_colors_name'), table_name='colors')
    op.drop_table('colors')
    # ### end Alembic commands ###

